# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from databricks.sdk._sandbox_grpc import sandbox_service_pb2 as databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in databricks/sdk/_sandbox_grpc/sandbox_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub:
    """Service for executing commands inside running sandboxes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCommand = channel.unary_stream(
                '/databricks.sandbox.SandboxService/ExecuteCommand',
                request_serializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ExecuteCommandResponse.FromString,
                _registered_method=True)
        self.AttachCommand = channel.unary_stream(
                '/databricks.sandbox.SandboxService/AttachCommand',
                request_serializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.AttachCommandRequest.SerializeToString,
                response_deserializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.AttachCommandResponse.FromString,
                _registered_method=True)
        self.StreamInput = channel.stream_unary(
                '/databricks.sandbox.SandboxService/StreamInput',
                request_serializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.StreamInputRequest.SerializeToString,
                response_deserializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.StreamInputResponse.FromString,
                _registered_method=True)
        self.ListCommands = channel.unary_unary(
                '/databricks.sandbox.SandboxService/ListCommands',
                request_serializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ListCommandsRequest.SerializeToString,
                response_deserializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ListCommandsResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer:
    """Service for executing commands inside running sandboxes.
    """

    def ExecuteCommand(self, request, context):
        """Executes a command inside the sandbox. Streams process lifecycle events back to the caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachCommand(self, request, context):
        """Attaches to a previously started command execution, streaming its output.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInput(self, request_iterator, context):
        """Streams stdin data to a running command.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCommands(self, request, context):
        """Lists all tracked command executions (running and completed).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCommand': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ExecuteCommandResponse.SerializeToString,
            ),
            'AttachCommand': grpc.unary_stream_rpc_method_handler(
                    servicer.AttachCommand,
                    request_deserializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.AttachCommandRequest.FromString,
                    response_serializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.AttachCommandResponse.SerializeToString,
            ),
            'StreamInput': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamInput,
                    request_deserializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.StreamInputRequest.FromString,
                    response_serializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.StreamInputResponse.SerializeToString,
            ),
            'ListCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCommands,
                    request_deserializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ListCommandsRequest.FromString,
                    response_serializer=databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ListCommandsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'databricks.sandbox.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('databricks.sandbox.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService:
    """Service for executing commands inside running sandboxes.
    """

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/databricks.sandbox.SandboxService/ExecuteCommand',
            databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ExecuteCommandRequest.SerializeToString,
            databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ExecuteCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/databricks.sandbox.SandboxService/AttachCommand',
            databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.AttachCommandRequest.SerializeToString,
            databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.AttachCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInput(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/databricks.sandbox.SandboxService/StreamInput',
            databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.StreamInputRequest.SerializeToString,
            databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.StreamInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/databricks.sandbox.SandboxService/ListCommands',
            databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ListCommandsRequest.SerializeToString,
            databricks_dot_sdk_dot___sandbox__grpc_dot_sandbox__service__pb2.ListCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
