change_types:
  - message: New Features and Improvements
    tag: "[Feature]"
  - message: Bug Fixes
    tag: "[Fix]"
  - message: Documentation
    tag: "[Doc]"
  - message: Internal Changes
    tag: "[Internal]"
  # Does not appear in the Changelog. Only for PR validation.
  - message: Release
    tag: "[Release]"
  # Default for messages without a tag
  - message: Other Changes