# Code generated by Databricks SDK Generator. DO NOT EDIT.

from dataclasses import dataclass


@dataclass
class Package:
    name: str
    label: str
    description: str


# Hand-curated entries. Edit these freely — manual entries always shadow the
# autogenerated ones below at import time, so adding or polishing a label here
# overrides whatever the spec produces.
MANUAL_PACKAGES = [
    Package("workspace", "Workspace",
            "Manage workspace-level entities that include notebooks, Git checkouts, and secrets"),
    Package("compute", "Compute", "Use and configure compute for Databricks"),
    Package("jobs", "Jobs", "Schedule automated jobs on Databricks Workspaces"),
    Package("pipelines", "Spark Declarative Pipelines",
            "Manage pipelines, runs, and other Spark Declarative Pipeline resources"),
    Package("files", "File Management", "Manage files on Databricks in a filesystem-like interface"),
    Package("ml", "Machine Learning",
            "Create and manage experiments, features, and other machine learning artifacts"),
    Package("serving", "Real-time Serving", "Use real-time inference for machine learning"),
    Package("iam", "Identity and Access Management",
            "Manage users, service principals, groups and their permissions in Accounts and Workspaces"),
    Package(
        "sql", "Databricks SQL",
        "Manage Databricks SQL assets, including warehouses, dashboards, queries and query history, and alerts"
    ),
    Package(
        "catalog", "Unity Catalog",
        "Configure data governance with Unity Catalog for metastores, catalogs, schemas, tables, external locations, and storage credentials"
    ),
    Package("sharing", "Delta Sharing",
            "Configure data sharing with Unity Catalog for providers, recipients, and shares"),
    Package("settings", "Settings", "Manage security settings for Accounts and Workspaces"),
    Package("settingsv2", "SettingsV2", "Manage admin settings"),
    Package("tags", "Tags", "Manage tag policies and tag assignments on workspace objects"),
    Package(
        "provisioning", "Provisioning",
        "Resource management for secure Databricks Workspace deployment, cross-account IAM roles, " +
        "storage, encryption, networking and private access."),
    Package("billing", "Billing", "Configure different aspects of Databricks billing and usage."),
    Package("oauth2", "OAuth", "Configure OAuth 2.0 application registrations for Databricks"),
    Package("vectorsearch", "Vector Search", "Create and query Vector Search indexes"),
    Package("dashboards", "Dashboards", "Manage Lakeview dashboards"),
    Package("marketplace", "Marketplace", "Manage AI and analytics assets such as ML models, notebooks, applications in an open marketplace"),
    Package("apps", "Apps", "Build custom applications on Databricks"),
    Package("cleanrooms", "Clean Rooms", "Manage clean rooms and their assets and task runs"),
    Package(
        "qualitymonitorv2",
        "Quality Monitor",
        "Manage quality monitor on Unity Catalog objects."
    ),
    Package(
        "database",
        "Database Instances",
        "Create Database Instances and manage their configurations, including integrations with Unity Catalog"
    ),
    Package(
        "agentbricks",
        "Agent Bricks",
        "Create and manage Agent Bricks resources."
    ),
    Package(
        "iamv2",
        "Identity and Access Management",
        "Manage identities and workspace access."
    ),
    Package(
        "dataquality",
        "Data Quality",
        "Manage data quality monitoring on Unity Catalog objects."
    ),
    Package(
        "postgres",
        "Postgres",
        "provides access to a Postgres database via REST API or direct SQL."
    ),
    Package(
        "networking",
        "Networking",
        "Manage network connectivity configurations for Databricks workspaces."
    ),
    Package(
        "knowledgeassistants",
        "Knowledge Assistants",
        "Manage Knowledge Assistants and related resources.",
    ),
    Package(
        "supervisoragents",
        "Supervisor Agents",
        "Manage Supervisor Agents and related resources.",
    ),
    Package(
        "dataclassification",
        "Data Classification",
        "Manage data classification for Unity Catalog catalogs.",
    ),
    Package(
        "environments",
        "Environments",
        "Manage workspace-level environments including base environments for serverless notebooks and jobs.",
    ),
    Package(
        "disasterrecovery",
        "Disaster Recovery",
        "Manage disaster recovery configurations and execute failover operations.",
    ),
]


# Autogenerated from the OpenAPI spec — one entry per sdk_package. Sourced from
# the package's tag display_name and description. Do not edit; promote an entry
# into MANUAL_PACKAGES above to override.
AUTO_PACKAGES = [
    Package("agentbricks", "Agent Bricks Service", "The Custom LLMs service manages state and powers the UI for the Custom LLM product."),
    Package("aisearch", "AISearch", "**AI Search Endpoint**: Represents the compute resources to host AI Search indexes. AIP-conformant replacement for the legacy VectorSearchEndpoints API; functionally equivalent."),
    Package("apps", "", ""),
    Package("billing", "", ""),
    Package("bundledeployments", "Bundle Deployments", "Service for managing bundle deployment metadata."),
    Package("catalog", "", ""),
    Package("cleanrooms", "", ""),
    Package("compute", "", ""),
    Package("dashboards", "", ""),
    Package("database", "Database Instances", "Database Instances provide access to a database via REST API or direct SQL."),
    Package("dataclassification", "Data Classification", "Manage data classification for Unity Catalog catalogs.\nData classification automatically identifies and tags sensitive data (PII) in Unity Catalog tables.\nEach catalog can have at most one configuration resource that controls scanning behavior and auto-tagging rules."),
    Package("dataquality", "Data Quality Monitors", "Manage the data quality of Unity Catalog objects (currently support `schema` and `table`)"),
    Package("disasterrecovery", "Disaster Recovery", "Manage disaster recovery configurations and execute failover operations."),
    Package("environments", "Environments API", "APIs to manage environment resources.\n\nThe Environments API provides management capabilities for different types of environments\nincluding workspace-level base environments that define the environment version and\ndependencies to be used in serverless notebooks and jobs."),
    Package("files", "", ""),
    Package("iam", "", ""),
    Package("iamv2", "", ""),
    Package("jobs", "", ""),
    Package("knowledgeassistants", "Knowledge Assistants", "Manage Knowledge Assistants and related resources."),
    Package("marketplace", "", ""),
    Package("ml", "", ""),
    Package("networking", "Networking Endpoints", "These APIs manage endpoint configurations for this account."),
    Package("oauth2", "", ""),
    Package("pipelines", "Pipelines", "The Lakeflow Spark Declarative Pipelines API allows you to create, edit, delete, start, and view details about pipelines.\n\nSpark Declarative Pipelines is a framework for building reliable, maintainable, and testable data processing pipelines. You define the transformations to perform on your data, and Spark Declarative Pipelines manages task orchestration, cluster management, monitoring, data quality, and error handling.\n\nInstead of defining your data pipelines using a series of separate Apache Spark tasks, Spark Declarative Pipelines manages how your data is transformed based on a target schema you define for each processing step. You can also enforce data quality with Spark Declarative Pipelines expectations. Expectations allow you to define expected data quality and specify how to handle records that fail those expectations."),
    Package("postgres", "Postgres", "Use the Postgres API to create and manage Lakebase Autoscaling Postgres infrastructure, including projects, branches, compute endpoints, and roles.\n\nThis API manages database infrastructure only. To query or modify data, use the Data API or direct SQL connections.\n\n**About resource IDs and names**\n\nResources are identified by hierarchical resource names like `projects/{project_id}/branches/{branch_id}/endpoints/{endpoint_id}`. The `name` field on each resource contains this full path and is output-only. Note that `name` refers to this resource path, not the user-visible `display_name`."),
    Package("provisioning", "", ""),
    Package("qualitymonitorv2", "Quality Monitor V2", "Deprecated: Please use the Data Quality Monitoring API instead (REST: /api/data-quality/v1/monitors). Manage data quality of UC objects (currently support `schema`)."),
    Package("serving", "", ""),
    Package("settings", "", ""),
    Package("settingsv2", "", ""),
    Package("sharing", "", ""),
    Package("sql", "", ""),
    Package("supervisoragents", "Supervisor Agents", "Manage Supervisor Agents and related resources."),
    Package("tags", "", ""),
    Package("vectorsearch", "", ""),
    Package("workspace", "", ""),
]


_manual_slugs = {p.name for p in MANUAL_PACKAGES}
_auto_unique = [p for p in AUTO_PACKAGES if p.name not in _manual_slugs]

# AUTO entries source their label from versioned_api.display_name and their
# description from the sole-service tag description. When either is missing
# (multi-service packages with no canonical per-package value, or single-service
# packages whose proto omits the field), refuse to ship a placeholder — labels
# feed into rendered H1 text and Sphinx anchor ids, which become permanent
# references once published. Force the caller to add a hand-curated
# MANUAL_PACKAGES entry rather than autogen a value that we can't safely
# change later.
_undocumented = [p.name for p in _auto_unique if not p.label or not p.description]
if _undocumented:
    raise RuntimeError(
        "Autogenerated packages with empty label or description need a "
        "MANUAL_PACKAGES entry — the spec doesn't supply enough metadata to "
        "ship them safely, and the generator refuses to invent values that "
        "would land in permanent rendered identifiers: "
        + ", ".join(sorted(_undocumented))
    )

PACKAGES = MANUAL_PACKAGES + _auto_unique