# Code generated by Databricks SDK Generator. DO NOT EDIT.

from dataclasses import dataclass


@dataclass
class Package:
    name: str
    label: str
    description: str


PACKAGES = [
    Package("workspace", "Workspace",
            "Manage workspace-level entities that include notebooks, Git checkouts, and secrets"),
    Package("compute", "Compute", "Use and configure compute for Databricks"),
    Package("jobs", "Jobs", "Schedule automated jobs on Databricks Workspaces"),
    Package("pipelines", "Spark Declarative Pipelines",
            "Manage pipelines, runs, and other Spark Declarative Pipeline resources"),
    Package("files", "File Management", "Manage files on Databricks in a filesystem-like interface"),
    Package("ml", "Machine Learning",
            "Create and manage experiments, features, and other machine learning artifacts"),
    Package("serving", "Real-time Serving", "Use real-time inference for machine learning"),
    Package("iam", "Identity and Access Management",
            "Manage users, service principals, groups and their permissions in Accounts and Workspaces"),
    Package(
        "sql", "Databricks SQL",
        "Manage Databricks SQL assets, including warehouses, dashboards, queries and query history, and alerts"
    ),
    Package(
        "catalog", "Unity Catalog",
        "Configure data governance with Unity Catalog for metastores, catalogs, schemas, tables, external locations, and storage credentials"
    ),
    Package("sharing", "Delta Sharing",
            "Configure data sharing with Unity Catalog for providers, recipients, and shares"),
    Package("settings", "Settings", "Manage security settings for Accounts and Workspaces"),
    Package("settingsv2", "SettingsV2", "Manage admin settings"),
    Package("tags", "Tags", "Manage tag policies and tag assignments on workspace objects"),
    Package(
        "provisioning", "Provisioning",
        "Resource management for secure Databricks Workspace deployment, cross-account IAM roles, " +
        "storage, encryption, networking and private access."),
    Package("billing", "Billing", "Configure different aspects of Databricks billing and usage."),
    Package("oauth2", "OAuth", "Configure OAuth 2.0 application registrations for Databricks"),
    Package("vectorsearch", "Vector Search", "Create and query Vector Search indexes"),
    Package("dashboards", "Dashboards", "Manage Lakeview dashboards"),
    Package("marketplace", "Marketplace", "Manage AI and analytics assets such as ML models, notebooks, applications in an open marketplace"),
    Package("apps", "Apps", "Build custom applications on Databricks"),
    Package("cleanrooms", "Clean Rooms", "Manage clean rooms and their assets and task runs"),
    Package(
        "qualitymonitorv2",
        "Quality Monitor",
        "Manage quality monitor on Unity Catalog objects."
    ),
    Package(
        "database",
        "Database Instances",
        "Create Database Instances and manage their configurations, including integrations with Unity Catalog"
    ),
    Package(
        "agentbricks",
        "Agent Bricks",
        "Create and manage Agent Bricks resources."
    ),
    Package(
        "iamv2",
        "Identity and Access Management",
        "Manage identities and workspace access."
    ),
    Package(
        "dataquality",
        "Data Quality",
        "Manage data quality monitoring on Unity Catalog objects."
    ),
    Package(
        "postgres",
        "Postgres",
        "provides access to a Postgres database via REST API or direct SQL."
    ),
    Package(
        "networking",
        "Networking",
        "Manage network connectivity configurations for Databricks workspaces."
    ),
    Package(
        "knowledgeassistants",
        "Knowledge Assistants",
        "Manage Knowledge Assistants and related resources.",
    ),
    Package(
        "supervisoragents",
        "Supervisor Agents",
        "Manage Supervisor Agents and related resources.",
    ),
    Package(
        "dataclassification",
        "Data Classification",
        "Manage data classification for Unity Catalog catalogs.",
    ),
    Package(
        "environments",
        "Environments",
        "Manage workspace-level environments including base environments for serverless notebooks and jobs.",
    ),
]