name: build

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  tests-ubuntu:
    uses: ./.github/workflows/test.yml
    strategy:
      fail-fast: false
      matrix:
        pyVersion: [ '3.8', '3.9', '3.10', '3.11', '3.12' ]
    with:
      os: ubuntu-latest
      pyVersion: ${{ matrix.pyVersion }}

  tests-windows:
      uses: ./.github/workflows/test.yml
      strategy:
        fail-fast: false
        matrix:
          pyVersion: [ '3.9', '3.10', '3.11', '3.12' ]
      with:
        os: windows-latest
        pyVersion: ${{ matrix.pyVersion }}
          
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Format all files
        run: make dev fmt

      - name: Fail on differences
        run: git diff --exit-code

  check-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: 3.13

      - name: Check MANIFEST.in
        run: |
          pip install check-manifest
          check-manifest .
