name: build

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]

permissions:
  id-token: write
  contents: read

jobs:
  tests-ubuntu:
    uses: ./.github/workflows/test.yml
    strategy:
      fail-fast: false
      matrix:
        pyVersion: [ '3.10', '3.11', '3.12' ]
    with:
      os: ubuntu-latest
      pyVersion: ${{ matrix.pyVersion }}

  tests-windows:
      uses: ./.github/workflows/test.yml
      strategy:
        fail-fast: false
        matrix:
          pyVersion: [ '3.10', '3.11', '3.12' ]
      with:
        os: windows-latest
        pyVersion: ${{ matrix.pyVersion }}

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          version: "0.6.5"

      - name: Setup JFrog PyPI proxy
        uses: ./.github/actions/setup-jfrog-pypi

      - name: Format all files
        run: make dev fmt UV_SYNC_FLAGS=--frozen UV_RUN_FLAGS=--frozen

      - name: Fix lockfile
        run: make fix-lockfile

      - name: Fail on differences
        run: git diff --exit-code

  check-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          version: "0.6.5"

      - name: Setup JFrog PyPI proxy
        uses: ./.github/actions/setup-jfrog-pypi

      - name: Check MANIFEST.in
        run: make dev UV_SYNC_FLAGS=--frozen UV_RUN_FLAGS=--frozen && uv run --frozen check-manifest .
