name: Release (TestPyPI)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on:
      group: databricks-deco-testing-runner-group
      labels: ubuntu-latest-deco

    environment: release-test

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: 3.13

      - name: Install build
        run: pip install --require-hashes -r requirements-build-lock.txt

      - name: Build wheel
        run: python -m build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        name: Publish package distributions to TestPyPI
        with:
          repository-url: https://test.pypi.org/legacy/
          # See https://github.com/pypa/gh-action-pypi-publish#tolerating-release-package-file-duplicates
          skip-existing: true
