name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on:
      group: databricks-deco-testing-runner-group
      labels: ubuntu-latest-deco

    environment: release

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          version: "0.6.5"

      - name: Build wheel
        run: uv build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Write release notes to file
        run: |
          RELEASE_NOTES_DIR=/tmp/release-notes
          mkdir -p "$RELEASE_NOTES_DIR"
          RELEASE_NOTES_FILE="$RELEASE_NOTES_DIR/release-notes.md"
          git for-each-ref --format='%(body)' ${{ github.ref }} > "$RELEASE_NOTES_FILE"
          echo "Release notes file: $RELEASE_NOTES_FILE"
          echo "Release notes contents:"
          cat "$RELEASE_NOTES_FILE"

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          body_path: /tmp/release-notes/release-notes.md
          files: |
            dist/databricks_*.whl
            dist/databricks_*.tar.gz

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        name: Publish package distributions to PyPI
