name: Test Workflow

on:
  workflow_call:
    inputs:
        os:
            required: true
            type: string
        pyVersion:
            required: true
            type: string

jobs:
  test:
    strategy:
        fail-fast: false
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.pyVersion }}

      - name: Run tests
        run: make dev install test

      - name: Publish test coverage
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}