name: Test Workflow

on:
  workflow_call:
    inputs:
        os:
            required: true
            type: string
        pyVersion:
            required: true
            type: string

jobs:
  test:
    strategy:
        fail-fast: false
        matrix:
            use-latest-deps:
              - true
              - false
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.pyVersion }}

      - name: Run tests
        run: |
          if [ "${{ matrix.use-latest-deps }}" = "true" ]; then
            make dev-latest test
          else
            make dev test
          fi

      - name: Publish test coverage
        if: ${{ !matrix.use-latest-deps }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}