name: Test Workflow

on:
  workflow_call:
    inputs:
        os:
            required: true
            type: string
        pyVersion:
            required: true
            type: string

jobs:
  test:
    strategy:
        fail-fast: false
        matrix:
            dep-type:
              - latest
              - frozen
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.pyVersion }}

      - name: Run tests
        shell: bash
        run: |
          if [ "${{ matrix.dep-type }}" = "latest" ]; then
            make dev-latest test
          else
            make dev test
          fi

      - name: Publish test coverage
        if: ${{ matrix.dep-type == 'frozen' }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}